import Head from 'next/head'
import localFont from '@next/font/local'
import { About } from './sections/About'
import { Header } from './sections/Header'
import { Sidebar } from './sections/Sidebar'
import { Canvas } from './sections/Canvas'

export default function Home() {
  return (
    <>
      <Head>
        <title>Carmelo Pullara - Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Sidebar />
      <main>
        <Canvas />
        <About />
      </main>
    </>
  )
}
